maidsafe/safe_examples

.gitignore, dns_example/README.md, dns_example/src/scripts/safe_api/safe_io.js
Libsodium dependency handled for linux
=> Libsodium dependency handling refactored

dns_example/README.md, dns_example/src/scripts/main.js, dns_example/src/scripts/safe_api/dns.js, dns_example/src/scripts/safe_api/nfs.js, dns_example/src/scripts/safe_api/request_manager.js
implementation with the logger initialisation in main.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/13)
=> MAID-1465 DNS and NFS functions

dns_example/index.js, dns_example/src/scripts/main.js, dns_example/src/scripts/safe_api/connection_manager.js, dns_example/src/scripts/safe_api/request_manager.js
fixes #17 Comments added for connection_manager and request_manager
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/19)
=> Application Quit IPC event integrated - fixes #17

.gitignore, demo_app/app/app.html, demo_app/app/scripts/controllers/manage_private_data_controller.js, demo_app/app/scripts/controllers/public_id_controller.js, demo_app/app/scripts/controllers/sample_template_controller.js, demo_app/app/scripts/controllers/service_controller.js, demo_app/app/scripts/directives/explorer.js, demo_app/app/scripts/directives/progress.js, demo_app/app/scripts/directives/prompt.js, demo_app/app/scripts/factories/safe_api_factory.js, demo_app/app/scripts/main.js, demo_app/app/views/manage_private_data.html, demo_app/app/views/progress.html, demo_app/app/views/prompt.html, demo_app/app/views/service_explorer.html
Implemented Progress bar and prompt UI components as directives.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/37)
=> UI Components - Progress bar and Prompt clean up

demo_app/app/backend/create_template_file.js, demo_app/app/backend/directory_helper.js, demo_app/app/backend/file_downloader.js, demo_app/app/backend/file_helper.js, demo_app/app/backend/uploader.js, demo_app/app/package.json, demo_app/app/scripts/controllers/sample_template_controller.js, demo_app/app/scripts/controllers/service_controller.js, demo_app/app/scripts/directives/explorer.js, demo_app/app/scripts/main.js, demo_app/config/env_development.json, demo_app/config/env_production.json, demo_app/config/env_test.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/40)
=> Uploader code refactored for handling one file upload at a time

dns_example/.jscsrc, dns_example/.jshintrc, dns_example/Gruntfile.js, dns_example/package.json, dns_example/src/scripts/main.js, dns_example/src/scripts/uploader.js
dns_example Jscs and Jshint validation implemented.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/27)
=> DNS Example - Jscs and Jshint validation

demo_app/app/backend/file_downloader.js, demo_app/app/backend/file_helper.js, demo_app/app/scripts/controllers/manage_private_data_controller.js, demo_app/app/scripts/controllers/public_id_controller.js, demo_app/app/scripts/controllers/sample_template_controller.js, demo_app/app/scripts/controllers/service_controller.js, demo_app/app/scripts/directives/explorer.js, demo_app/app/scripts/directives/progress.js, demo_app/app/scripts/directives/prompt.js, demo_app/app/scripts/factories/safe_api_factory.js, demo_app/app/scripts/main.js
Based on the [CS-8](https://maidsafe.atlassian.net/projects/CS/issues/CS-8) issue reported, the download of files above 500kb were corrupted. The issue is resolved in this PR.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/44)
=> File download issue resolved

demo_app/app/app.js, demo_app/app/backend/file_helper.js, demo_app/app/scripts/controllers/service_controller.js, demo_app/app/scripts/directives/explorer.js, demo_app/app/scripts/directives/progress.js
Disabled drag and drop. Fixes the issue of the application opening up the content when the user drags and drops files into the application.
Issue reported while Uploading files of size 0 bytes have been fixed
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/45)
=> Minor bug fixes

demo_app/CHANGELOG.MD, demo_app/app/package.json, demo_app/app/scripts/controllers/authorise_controller.js, demo_app/app/scripts/controllers/public_id_controller.js, demo_app/app/scripts/controllers/service_controller.js, demo_app/app/scripts/factories/safe_api_factory.js, demo_app/app/stylesheets/components.less, demo_app/app/stylesheets/prompt.less, demo_app/app/stylesheets/variables.less, demo_app/app/views/authorisation.html
Demo app Authorisation UI changes and Public ID error handling integrated
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/46)
=> Demo app Authorisation UI changes and Public ID error handling

demo_app/CHANGELOG.MD, demo_app/config/env_development.json, demo_app/config/env_production.json, demo_app/config/env_test.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/47)
=> File size restriction updated to 5 mb

demo_app/CHANGELOG.MD
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/49)
=> version change log updated

demo_app/app/backend/file_helper.js, demo_app/app/scripts/factories/nfs_factory.js
`localFilePath` parameter is used for uploading the content of the file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/54)
=> Create file API update

demo_app/tasks/package.js
Packaging fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/55)
=> Packaging fixes

demo_app/app/scripts/controllers/authorise_controller.js, demo_app/app/scripts/controllers/service_controller.js, demo_app/app/scripts/directives/explorer.js, demo_app/app/scripts/factories/safe_api_factory.js
Removed encryption/decryption from API calls.
Removed unwanted JSON parsing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/70)
=> Removed encryption/decryption from API calls

demo_app/CHANGELOG.MD, demo_app/app/package.json
- Safe launcher v0.5 compatibility
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/74)
=> version change to 0.3

demo_app/app/backend/directory_helper.js, demo_app/app/backend/file_downloader.js, demo_app/app/backend/file_helper.js, demo_app/app/package.json, demo_app/app/scripts/controllers/authorise_controller.js, demo_app/app/scripts/controllers/public_id_controller.js, demo_app/app/scripts/controllers/sample_template_controller.js, demo_app/app/scripts/controllers/service_controller.js, demo_app/app/scripts/directives/explorer.js, demo_app/app/scripts/directives/prompt.js, demo_app/app/stylesheets/prompt.less, demo_app/app/views/prompt.html
implemented to display FFI errors on UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/75)
=> Error handling

demo_app/app/scripts/controllers/public_id_controller.js, demo_app/app/scripts/controllers/service_controller.js, demo_app/app/scripts/factories/nfs_factory.js
Resolves file upload error being handled,
Service name and public name validation improved
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/76)
=> fix/file_stream: Resolve file upload error

demo_app/app/scripts/controllers/public_id_controller.js, demo_app/app/scripts/controllers/service_controller.js
Updated the validation message to inform the user about the minimum length required for service name and public name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/77)
=> Service and public name validation messsage updated

demo_app/CHANGELOG.MD, demo_app/app/package.json
- Error handling for file upload streaming
- validation for service and public names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/78)
=> version change to 0.3.1

demo_app/app/scripts/controllers/public_id_controller.js, demo_app/app/scripts/directives/explorer.js, demo_app/app/scripts/factories/safe_api_factory.js
Initialisation check to identify launcher state resolved
Upload dialog box title typo fixed
Public ID creation on error typo fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/86)
=> Updated typo and resolved app initialisation

demo_app/app/backend/file_helper.js, demo_app/app/scripts/controllers/public_id_controller.js, demo_app/app/scripts/controllers/sample_template_controller.js, demo_app/app/scripts/controllers/service_controller.js, demo_app/app/scripts/directives/progress.js, demo_app/app/scripts/directives/prompt.js, demo_app/app/scripts/factories/nfs_factory.js
Fixes #84
- Error message overflowing outside the dialog box is handled
- Progress bar while uploading files and folders have been updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/88)
=> fix/ui_patch: resolve file upload issue

demo_app/app/scripts/factories/nfs_factory.js
Fixes #79.
A temporary patch. Exact fix to follow in the next version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/89)
=> fix/delete_file: delete file if file upload fails

demo_app/app/backend/file_helper.js, demo_app/app/scripts/factories/nfs_factory.js
Upload file content using create file api of NFS with streaming support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/91)
=> fix/creat_file_api: update create file api to stream content

demo_app/CHANGELOG.MD, demo_app/app/package.json
- File size limit increased to 50 MB
- Compatibility with safe launcher v0.6.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/94)
=> version change to v0.4.0

demo_app/CHANGELOG.MD, demo_app/app/package.json
- New UI workflow integration
- Separation of website and network data management
- Ability to cancel uploads
- Show file count status while uploading folders
- Open the download folder instead of opening the downloaded file
- Initial root folder creation failure recovery
- Show initial authorisation stages on loading
- Ability to remap service home directory
- Option to delete a service
- various bug fixes and UX updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/107)
=> Version change to 0.5.0

demo_app/app/scripts/controllers/authorise_controller.js
application should close for non 401 error codes while authorisation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/108)
=> fix/handle_authorisation_failure: close application on authorisation

demo_app/CHANGELOG.MD, demo_app/app/package.json
- Close application on authorisation failure
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/109)
=> version change to 0.5.1

demo_app/app/package.json, demo_app/tasks/package.js
Add appversion to electron packager command
Added copyright to app's package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/112)
=> fix/package_fix: fix packaging issue

demo_app/app/backend/create_template_file.js, demo_app/app/backend/directory_helper.js, demo_app/app/backend/file_downloader.js, demo_app/app/backend/file_helper.js, demo_app/app/backend/uploader.js, demo_app/app/scripts/controllers/authorise_controller.js, demo_app/app/scripts/controllers/manage_network_data_controller.js, demo_app/app/scripts/controllers/public_id_controller.js, demo_app/app/scripts/controllers/sample_template_controller.js, demo_app/app/scripts/controllers/service_controller.js, demo_app/app/scripts/directives/explorer.js, demo_app/app/scripts/directives/field_focus.js, demo_app/app/scripts/directives/progress.js, demo_app/app/scripts/factories/nfs_factory.js, demo_app/app/scripts/main.js, demo_app/gulpfile.js, demo_app/package.json, demo_app/tasks/linter.js, demo_app/tasks/mocha-test.js, demo_app/tasks/package.js
Linter integrated and lint errors cleaned.
Packaging task updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/116)
=> Resolve lint errors

demo_app/README.md, demo_app/app/backend/create_template_file.js, demo_app/app/backend/directory_helper.js, demo_app/app/backend/file_downloader.js, demo_app/app/backend/file_helper.js, demo_app/app/backend/uploader.js, demo_app/app/scripts/controllers/authorise_controller.js, demo_app/app/scripts/controllers/manage_network_data_controller.js, demo_app/app/scripts/controllers/public_id_controller.js, demo_app/app/scripts/controllers/sample_template_controller.js, demo_app/app/scripts/controllers/service_controller.js, demo_app/app/scripts/directives/explorer.js, demo_app/app/scripts/directives/field_focus.js, demo_app/app/scripts/directives/progress.js, demo_app/app/scripts/factories/nfs_factory.js, demo_app/app/scripts/main.js, demo_app/gulpfile.js, demo_app/package.json, demo_app/tasks/linter.js, demo_app/tasks/mocha-test.js, demo_app/tasks/package.js, demo_app/tasks/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/117)
=> jscs and jshint integration

demo_app/CHANGELOG.MD, demo_app/app/package.json
- Compatibility with launcher 0.8.0
- Rename files and folders
- Cut/Copy files and folders
- Packaging fixes
- Minor style fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/118)
=> version change to 0.6.0

demo_app/app/scripts/controllers/public_id_controller.js, demo_app/app/scripts/controllers/service_controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/122)
=> Fix grammar in validation error messages

demo_app/app/views/create_service.html, demo_app/app/views/manage_public_id.html, demo_app/app/views/manage_service.html
Updated protocol from http:// to safe://
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/126)
=> feat/protocol_change: update protocol from http to safe

demo_app/app/views/create_service.html, demo_app/app/views/manage_public_id.html
.safenet has been removed from SAFE Url
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/127)
=> typo/safe_url: update safe url without .safenet

demo_app/app/views/manage_service.html
Updated service list safe url without .safenet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/129)
=> typo/safe_url: update safe url in service list

demo_app/CHANGELOG.MD, demo_app/app/package.json
- Reverse DNS specifier updated in package.json
- Updated service links on UI to `safe://` scheme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/130)
=> demo app - version change to 0.6.1

email_app/app/actions/data_id_handle_actions.js, email_app/app/actions/structured_data_actions.js, email_app/app/components/initializer.js, email_app/app/constants.js, email_app/app/containers/initializer_container.js
Resolved Structured Data default type tag as 500 and versioned as 501.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_examples/136)
=> fix/type_tag_mismatch: resolve structured data type tag mismatch issue

email_app/CHANGELOG.md, email_app/package.json
- Unversioned Tag Type Corrected
- Compatible with launcher version 0.9.2
=> version change to 0.1.2

editable_comments_plugin/comments/src/controller.js, permanent_comments_plugin/comments/src/controller.js
Updated to support latest safe browser 0.4.0
=> fix/support_latest_safe_browser: update to support latest safe browser 0.4.0

README.md, web_hosting_manager/README.md
Updated Readme for web_hosting_manager
=> chore/readme: updated readme

email_app_java/README.md, email_app_java/pom.xml, email_app_java/src/main/java/net/maidsafe/example/mail/controller/AppController.java, email_app_java/src/main/java/net/maidsafe/example/mail/controller/IdCreationController.java, email_app_java/src/main/java/net/maidsafe/example/mail/controller/InitialisationController.java, email_app_java/src/main/java/net/maidsafe/example/mail/dao/IMessagingDao.java, email_app_java/src/main/java/net/maidsafe/example/mail/dao/IRestAPI.java, email_app_java/src/main/java/net/maidsafe/example/mail/dao/LauncherAPI.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/AppConfig.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/AppInfo.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/AppendableDataCreateRequest.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/AppendableDataDataId.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/AppendableDataMetadata.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/AuthRequest.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/AuthResponse.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/FileResponse.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/HandleIdResponse.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/Message.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/ReaderInfo.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/Result.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/StructuredDataCreateRequest.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/StructuredDataDataId.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/StructuredDataMetadata.java, email_app_java/src/main/java/net/maidsafe/example/mail/modal/StructuredDataUpdateRequest.java, email_app_java/src/main/java/net/maidsafe/example/mail/scene/BaseScene.java, email_app_java/src/main/java/net/maidsafe/example/mail/scene/HomeScene.java, email_app_java/src/main/java/net/maidsafe/example/mail/scene/IdCreationScene.java, email_app_java/src/main/java/net/maidsafe/example/mail/scene/InitialisationScene.java, email_app_java/src/main/java/net/maidsafe/example/mail/util/ServiceHandler.java
- Sort message list
- Update Readme
=> Java email app

web_hosting_manager/app/lib/api.js
Updated to latest safe_app_nodejs crypto API.
=> Web hosting manager - Update to latest safe_app_nodejs

web_hosting_manager/app/lib/api.js, web_hosting_manager/app/lib/utils.js
Update to use safe crypto sha for public name.
=> Web hosting app - Update to use safe crypto sha

markdown_editor/src/store.js
=> MD Editor - Update crypto to safeCrypto

markdown_editor/src/config.js, markdown_editor/src/store.js
Updated to use home container to store datas instead of using _public container
=> MD Editor - Use home container

email_app/app/safenet_comm.js
This depends on PR [#73](https://github.com/maidsafe/safe_app_nodejs/pull/73) in `safe_app_nodejs`.
=> fix/Adapt to latest safe_app_nodejs and minor fix

markdown_editor/src/components/app.js, markdown_editor/src/store.js
Resolved read file issue and typo changed from Launcher to Authenticator
=> Read file issue

web_hosting_manager/app/actions/app.js, web_hosting_manager/app/components/CreateService.js, web_hosting_manager/app/components/FileExplorer.js, web_hosting_manager/app/lib/api.js, web_hosting_manager/app/lib/tasks.js, web_hosting_manager/app/reducers/access_info.js, web_hosting_manager/app/reducers/containers.js, web_hosting_manager/app/reducers/file.js, web_hosting_manager/app/reducers/public_id.js, web_hosting_manager/app/reducers/service.js, web_hosting_manager/app/styles/app.css, web_hosting_manager/app/utils/app_utils.js
=> Hosting app: UI related issues

web_hosting_manager/app/actions/app.js, web_hosting_manager/app/components/Auth.js, web_hosting_manager/app/components/CreateService.js, web_hosting_manager/app/components/FileExplorer.js, web_hosting_manager/app/components/Home.js, web_hosting_manager/app/containers/AuthPage.js, web_hosting_manager/app/containers/CreateService.js, web_hosting_manager/app/containers/FileExplorer.js, web_hosting_manager/app/containers/HomePage.js, web_hosting_manager/app/index.js, web_hosting_manager/app/lib/api.js, web_hosting_manager/app/locales/en.js, web_hosting_manager/app/reducers/auth.js, web_hosting_manager/app/styles/ant_customisation.css, web_hosting_manager/app/styles/app.css, web_hosting_manager/package.json
Updated to handle auth response and revoke.
=> Handle auth response

web_hosting_manager/app/lib/Downloader.js, web_hosting_manager/app/lib/api.js, web_hosting_manager/app/lib/tasks.js, web_hosting_manager/app/utils/app_utils.js
Resolve tagtype issue of service Data.
File update after deleted resolved.
Error description UI issue fixed.
=> Resolve tagtype issue

web_hosting_manager/app/components/Auth.js, web_hosting_manager/app/components/NetworkStatus.js, web_hosting_manager/app/constants.js, web_hosting_manager/app/lib/utils.js, web_hosting_manager/app/package.json, web_hosting_manager/app/reducers/access_info.js, web_hosting_manager/app/styles/app.css, web_hosting_manager/package.json
Disables file explorer upload dropdown user selection.
Rephrase error message on alerts.
Disable local storage.
=> MAID-2096 Safe Hosting app UI fixes

email_app/app/utils/app_utils.js
Remove local storage to ensure the keys are not stored locally
=> feat/no_local_key_trace: remove local storage

web_hosting_manager/app/locales/en.js, web_hosting_manager/app/package.json, web_hosting_manager/package.json
Updated app name following fix #201
=> Update app name

web_hosting_manager/app/styles/ant_customisation.css, web_hosting_manager/app/styles/app.css
=> MAID-2131 Web Hosting manager - Text overflow UI issue

web_hosting_manager/app/constants.js, web_hosting_manager/app/lib/api.js
Web hosting app - use NFS delete API
=> MAID-2156 Update delete file api

web_hosting_manager/app/actions/app.js, web_hosting_manager/app/index.js, web_hosting_manager/app/lib/Uploader.js, web_hosting_manager/app/main.development.js
Disable drag and drop.
Show upload error if file size is larger then 20Mb.
Menu added with `Simulate mock response`
=> MAID-2211 resolve minor ui issues

safe_web_api_playground/static/css/styles.css, safe_web_api_playground/static/js/client-scripts.js, safe_web_api_playground/static/js/code-snippets/safeApp.js
https://github.com/maidsafe/beaker-plugin-safe-app/blob/master/src/api/app.js#L210
=> implement `authoriseShareMd` for web API tool playground

web_hosting_manager/app/lib/utils.js
Works with with @hunterlester's PR 
https://github.com/maidsafe/safe_examples/pull/252
=> fix/emptyDirs: MAID-2306 Prevent empty dir upload crashes 

web_hosting_manager/app/package.json, web_hosting_manager/package.json
Resolve app version issue. Changed from  v0.1.3 to v0.2.1
=> Resolve app version number

web_hosting_manager/README.md, web_hosting_manager/app/components/FileExplorer.js, web_hosting_manager/app/components/PublicNames.js, web_hosting_manager/app/components/WizardNav.js, web_hosting_manager/app/components/_Header.js, web_hosting_manager/app/constants.js, web_hosting_manager/app/stylus/header.styl
- Readme notes on development.
- Move the connection icon back to the end of the logo
- Add simple tooltips for buttons
=> Web hosting enhancements

web_hosting_manager/CHANGELOG.md, web_hosting_manager/app/package.json, web_hosting_manager/package.json
CHANGELOG
- Fix upload website using a template issue
- Add tool tips for icons
- Fix the reconnect icon position
=> version change: web_hosting_manager 0.4.1

non-editable-comments-web/src/safe_api.js
vendor name updated to MaidSafe.net Ltd
=> fix/vendor_name: updated vendor name

non-editable-comments-web/src/safe_api.js
reload list after posting and deleting comment
=> comments_plugin/fix: reload list

web_hosting_manager/app/safenet_comm/helpers/utils.js
Resolved path separator issue on upload
=> Resolve path separator issue

email_app/CHANGELOG.md, email_app/package-lock.json, email_app/package.json, web_hosting_manager/CHANGELOG.md, web_hosting_manager/app/package.json, web_hosting_manager/app/yarn.lock, web_hosting_manager/package.json, web_hosting_manager/yarn.lock
I'll update `CHANGELOG` once PR #354 is merged.
=> chore/dependency: updates electron to 1.7.11

README.md
=> README.md: Change hosing to hosting

safe_web_api_playground/index.html, safe_web_api_playground/package.json, safe_web_api_playground/yarn.lock
Resolves https://github.com/maidsafe/safe_browser/issues/726
=> fix/playground: resolves jQuery issue and adds back OpenSans fonts
